### ISSUE TITLE
remove merged feature branches locally

### ISSUE THREAD

**Issue by teemow** [giantswarm/builder#11]
On my machine I have an alias like that 

```bash
alias rmmerged='git branch --merged master | grep -v "master$" | xargs git branch -d'
```

Every time I finished a feature, I checkout the master branch, pull the master, and execute `rmmerged` to remove the merged feature branch.

Maybe we want to have that in builder too. Ideas? @denderello @zeisss 

Original Author: @zyndiecate
Created at 18-09-2014 13:20:22
Gitlab: [giantswarm/builder!12](https://git.giantswarm.io/giantswarm/builder/issues/12)

**Comment by zeisss** [comment]
Decided not to do this.
