### ISSUE TITLE
Add a configuration file for builder to projects

### ISSUE THREAD

**Issue by teemow** [giantswarm/builder#2]
As we realize that more and more projects are getting complex in their setup it might be a good option to introduce a configuration file for builder that can be commited to the repository.

I would vote for a solution that has a fallback to run `semver-bump`, `make`, `docker` and `git` and default to push to the private registry if a `Dockerfile` is present. Cases like public images could be configured in the configuration file as well as things like special make targets that can be executed etc.

This way we can configure the projects independently instead of waiting for new builder releases or hacks for quick wins.

What do you think? @teemow @zyndiecate @zeisss @ewout @******* @marian 

Original Author: @denderello
Created at 20-01-2015 08:58:44
Gitlab: [giantswarm/builder!25](https://git.giantswarm.io/giantswarm/builder/issues/25)

**Comment by zeisss** [comment]
We have a config file, although currently only the public-release is configurable. Good enough.
