### ISSUE TITLE
add command to push image to docker hub

### ISSUE THREAD

**Issue by teemow** [giantswarm/builder#3]
When using `builder`, I often forget to use the `-p` flag to push images to docker hub. Means when you want to release the `ambassador` and forget using `-p`, you need to manually push the new image to the docker hub. A command would be helpful to do that, in case one forgot that.

Original Author: @zyndiecate
Created at 14-01-2015 15:27:48
Gitlab: [giantswarm/builder!24](https://git.giantswarm.io/giantswarm/builder/issues/24)

**Comment by zeisss** [comment]
we now have a config file where you can tell builder that a release should always be pushed to the docker hub. This way you can't forget.
