### ISSUE TITLE
"docker push" issues with docker 1.9

### ISSUE THREAD

**Issue by marians** [giantswarm/builder#62]
Could it be that builder isn't working well with docker version 1.9? or maybe the problem lies somewhere else, however I am getting this error:

```
...
Step 12 : EXPOSE 80
 ---> Running in fad4ae19f526
 ---> 0ddbb47a6e94
Removing intermediate container fad4ae19f526
Successfully built 0ddbb47a6e94
docker tag -f registry.giantswarm.io/giantswarm/docs:0.51.3 registry.giantswarm.io/giantswarm/docs
docker push registry.giantswarm.io/giantswarm/docs:0.51.3
The push refers to a repository [registry.giantswarm.io/giantswarm/docs] (len: 1)
Sending image list
Looks like something went wrong during the release process:


	The following command failed:
	
		docker push registry.giantswarm.io/giantswarm/docs:0.51.3
	
	Ouput of stdout was:
	
		The push refers to a repository [registry.giantswarm.io/giantswarm/docs] (len: 1)
	Sending image list
	
	
	Output of stderr was:
	
		Error: Status 404 trying to push repository giantswarm/docs: "404 page not found\n"
	


Rolling back changes that have been made during the release process
Checking if a git release tag has been created
git tag -l 0.51.3
0.51.3
Removing generated git release tag
git tag -d 0.51.3
Deleted tag '0.51.3' (was 99bc2f6)
Checking if there are unstaged git changes
git diff
```

The command

```
docker push registry.giantswarm.io/giantswarm/docs:0.51.3
```

works just fine.

**Comment by zeisss** [comment]
Are you using `sudo` or sthg that changes your home directory for the `builder` process? Afaik 404 can also appear if you are not logged in.

**Comment by marians** [comment]
No, not using sudo.

**Comment by denderello** [comment]
Most of the times 404 happens when the docker clients try to perform a registry v1 downgrade. But I think Docker 1.9 is the first version that is not using v1 registries anymore.

I would highly doubt, that `builder` is the problem here since it only calls `docker build` and `docker push` commands. I would rather suspect the registry to be point of failure here.

**Comment by zeisss** [comment]
Maybe the missing tags route is used by docker 1.9?

**Comment by zeisss** [comment]
is this still occuring?

**Comment by marians** [comment]
Don't know, I don't use 1.9 any more.

**Comment by denderello** [comment]
I am using `builder` with Docker 1.9.1 since it was available and never had problems. I would assume this is not an issue anymore.

**Comment by zeisss** [comment]
Cool, thanks. Closing.
