### ISSUE TITLE
Add support for Github Releases

### ISSUE THREAD

**Issue by JosephSalisbury** [giantswarm/builder#63]
We're now using Github Releases for open-source projects, but builder doesn't automatically do this for you, and this makes me sad.

I propose an addition to the release workflow (that is, these steps would run after the current `release` command) along the lines of:
- Create new Github release with release tag,
- Run `make bin-dist`,
- Upload all artifacts in the `bin-dist` folder to the newly created release,

**Comment by JosephSalisbury** [comment]
ping @teemow - i'd like to consider this in the next planning

**Comment by teemow** [comment]
:+1:
