### ISSUE TITLE
Add support for `make bin-dist`

### ISSUE THREAD

**Issue by JosephSalisbury** [giantswarm/builder#66]
We've been using the `make bin-dist` target as a binary on github releases, builder should handle this

**Comment by zeisss** [comment]
If we do this, we should write some documentation for what the goal of that target is etc.

**Comment by JosephSalisbury** [comment]
Yeah, we need documentation on the interface between `make` and `builder

**Comment by JosephSalisbury** [comment]
I'm closing this, as https://github.com/giantswarm/builder/issues/63 supersedes it
