### ISSUE TITLE
Add config for always pushing to public repo

### ISSUE THREAD

**Issue by JosephSalisbury** [giantswarm/builder#72]
We sometimes need to push docker images to multiple repos, which is currently a bit of a pain.
Would be good to have a minimal config file:
```
{
   docker-repositories: ["hub.docker.com", "registry.private.giantswarm.io"]
}
```
which pushes image to given repositories.
if no file is found, the current behaviour is used

ping @zeisss

**Comment by zeisss** [comment]
:white_check_mark:

**Comment by denderello** [comment]
:+1:

**Comment by JosephSalisbury** [comment]
Had a little chat with @zeisss:

Stricter problem definition:
- Some repositories are _always_ meant to be pushed to docker hub, but the default is that `builder` does not push to docker hub. For these repositories, it is very easy to forget to push to docker hub.

Simpler solution:
- check for `builder.json` in directory
- if `builder.json` present, and has `push_to_docker_hub: true` set, set the `-p` flag true

While it probably would be best to use `viper` for this, it seems slightly overkill at the moment - I'm fine with refactoring this later if we find ourselves needing multiple configuration values.
