### ISSUE TITLE
Add support for uploading multiple assets to Github release

### ISSUE THREAD

**Issue by JosephSalisbury** [giantswarm/builder#74]
Currently, the github release workflow will only upload one tarball to the github release, it would be useful if it could upload multiple

- [x] Add support to builder to upload multiple tarballs
- [x] Update builder to upload multiple tarballs
- [x] Release new builder version
- [x] Update inago to upload multiple tarballs
- [x] Update kocho to upload multiple tarballs
- [x] Update swarm-cli to upload multiple tarballs
- [ ] Update releaseit to upload multiple tarballs

cc @zeisss

**Comment by zeisss** [comment]
Ack, for now this probably makes sense for the following projects

* builder
* kocho
* formica
* our swarm-cli
* releaseit (internal)

**Comment by JosephSalisbury** [comment]
@zeisss this came up today, during the `inago` release. I'd like to note it particularly for the next planning.

**Comment by JosephSalisbury** [comment]
(assigning myself so I won't forget about it :D )

**Comment by zeisss** [comment]
moving back to inbox, so we see it again.

**Comment by JosephSalisbury** [comment]
@zeisss i've added a todo list of the repos that need updating to make use of this, which I'll do after I've merged and released

**Comment by JosephSalisbury** [comment]
We're not adding it to releaseit, no benefit. We're done here! :tada:
