### ISSUE TITLE
Personalized github token scope

### ISSUE THREAD

**Issue by teemow** [giantswarm/builder#87]
The environment variable is called `GITHUB_PERSONAL_ACCESS_TOKEN`. Imo it would be better to call it `BUILDER_GITHUB_PERSONAL_ACCESS_TOKEN`. I might have other tools that use the Github API and I want to be able to give each token different scopes.

The scopes that are necessary are not specified in the README of builder. It would be helpful to other people if they know which scopes are needed.

**Comment by zeisss** [comment]
@teemow Hey, we have renamed the variable to `BUILDER_GITHUB_TOKEN` in #91. This will be part of the next release.

**Comment by JosephSalisbury** [comment]
And that next release is [here!](https://github.com/giantswarm/builder/releases/tag/0.15.0)
