### ISSUE TITLE
Make builder release

### ISSUE THREAD

**Issue by zeisss** [giantswarm/builder#93]
was in the wrong repo: https://github.com/giantswarm/inago/issues/202

@zeisss
> Since we changed the var in #91 we should do a release of builder. Please also provide a nicer response in #87 to teemow after this was published.

@JosephSalisbury 
> We might as well wait till giantswarm/builder#88 is fixed

**Comment by JosephSalisbury** [comment]
Done with https://github.com/giantswarm/builder/releases/tag/0.15.0
