### ISSUE TITLE
-f flag is deprecated in Docker 1.10, and removed in upcoming release 1.12

### ISSUE THREAD

**Issue by oponder** [giantswarm/builder#98]
Running `Docker version 1.12.0-rc4, build e4a0dbc, experimental`

When I run builder, I get the following error at the tagging step:

```
Looks like something went wrong during the release process:


    The following command failed:

        docker tag -f registry.giantswarm.io/giantswarm/giantswarmio-webapp:0.12.7 registry.giantswarm.io/giantswarm/giantswarmio-webapp

    Output of stderr was:

        unknown shorthand flag: 'f' in -f
    See 'docker tag --help'.
```

Looks like the -f flag has been deprecated, and is removed in 1.12

https://docs.docker.com/engine/deprecated/#/f-flag-on-docker-tag

**Comment by puja108** [comment]
Why are we using `-f` with `tag` anyway, doesn't seem needed. ping @giantswarm/dev

**Comment by zeisss** [comment]
it was needed to overwrite latest, but this behavior now changed.

**Comment by zeisss** [comment]
We probably just need to drop it from here: https://github.com/giantswarm/builder/blob/master/docker/docker.go#L101

@oponder feel up for the task? 🍰

**Comment by hectorj2f** [comment]
which version doesn't it need it ?

**Comment by denderello** [comment]
It was deprecated in Docker version 1.10. See https://docs.docker.com/engine/deprecated/#/f-flag-on-docker-tag

Oh, btw. Hi Giant Swarm! 😸

**Comment by puja108** [comment]
@zeisss @oponder is still afk

**Comment by hectorj2f** [comment]
I'll cook a PR then

**Comment by puja108** [comment]
fixed as of https://github.com/giantswarm/builder/pull/99
